default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: ervin
  password: postgres
  pool: 5

development:
  <<: *default
  database: blog_hotwire_development


test:
  <<: *default
  database: blog_hotwire_test

